### PR TITLE
AlwaysFail property

### LINKED ISSUE #6: "Always Fail" style property
Testing validators or minting policies often only tests if they are "failing" correctly with certain input. Having "always fail" interface will provide a simpler way to build tests for certain types of scripts.

```hs
-- repeated pattern:
expected :: Term s (PBuiltinPair PTreasuryWithdrawalDatum PTxInfo :--> PMaybe PUnit)
expected = plam $ \_ -> pcon $ PNothing
```

### PR DESCRIPTION
**Pull request by SeungheonOh**
```
    faster (using alwaysFailProperty):                 OK (0.23s)
      +++ OK, passed 6400 tests:
      50.30% EvenNumber
      49.70% OddNumber
    slower (using classifiedProperty):                 OK (0.27s)
      +++ OK, passed 6400 tests:
      50.77% EvenNumber
      49.23% OddNumber
```

Noticeable performance boost as `alwaysFailProperty` will only run script once when it is expected to crash.  

Should close #6

### CODE REVIEW

File: src/Test/Tasty/Plutarch/Property.hs [hunk 1]
```diff
@@ -193,6 +196,61 @@ classifiedProperty getGen shr getOutcome classify comp = case cardinality @ix of
                                             Left e' -> failCrashyGetOutcome e'
                                             Right s' -> crashedWhenItShouldHave e s'
 
+{- | `alwaysfailproperty` operates similarly to `classifiedProperty` but optimized
+ for cases that will always fail. Scripts will only run once and will have some
+ considerable performance benefit as compared to `classifiedProperty`.
+-}
+alwaysFailProperty ::
```
Comment (kozross) [inline src/Test/Tasty/Plutarch/Property.hs]: I don't think this really makes sense as a conditional property. If you expect it to _always_ fail, then it's universal IMHO.

**Review by kozross — CHANGES_REQUESTED** [review]
This also needs a minor bump and a changelog entry: version 1.0.1.

File: CHANGELOG.md [hunk 2]
```diff
@@ -7,3 +7,15 @@ This format is based on [Keep A Changelog](https://keepachangelog.com/en/1.0.0).
...
+
+### Added
+
+* `alwaysFailProperty` -- an universial property that ensures script always fails
+
+### Fixed
+
+* Bug that made `classifiedProperty` fail to differentiate between
+  wrong result and expected crash when script ran without
+  crashing. (Fixed #5)
```
Comment (kozross) [inline CHANGELOG.md:15]: I believe the convention is that more recent changelogs go earlier in the list than older ones. Does KeepAChangelog specify otherwise? It's more convenient for readers.

File: src/Test/Tasty/Plutarch/Property.hs [hunk 3]
```diff
@@ -19,6 +19,9 @@ module Test.Tasty.Plutarch.Property (
 
     -- * Coverage-based properties
     classifiedProperty,
+
+    -- * Calssified property optimized for cases that always fails
+    alwaysFailProperty,
```
Comment (kozross) [inline src/Test/Tasty/Plutarch/Property.hs]: I'd probably label this without mentioning 'classified properties' at all. It's not technically a term (universal and conditional properties are the terms we use), and it's not really 'classified' anyway.

File: src/Test/Tasty/Plutarch/Property.hs [hunk 4]
```diff
@@ -102,6 +105,38 @@ peqProperty expected gen shr comp =
                 Left e -> unexpectedError e
                 Right s' -> sameAsExpected s'
 
+{- | `alwaysfailproperty` universially checks if given computation fails.
```
Comment (kozross) [inline src/Test/Tasty/Plutarch/Property.hs]: You want to wrap this in single quotes, because that creates a Haddock link.

Comment (kozross) [reply src/Test/Tasty/Plutarch/Property.hs]: Also, spelling.

File: src/Test/Tasty/Plutarch/Property.hs [hunk 5]
```diff
@@ -102,6 +105,38 @@ peqProperty expected gen shr comp =
...
+ This function operates very similarly to `peqProperty` but just checking
+ for the failures. Since output does not need to be checked, `PEq` instance
+ is not required.
```
Comment (kozross) [inline src/Test/Tasty/Plutarch/Property.hs]: This probably needs elaboration: specify that we check for _crashes_ or _errors_, rather than anything else.

File: src/Test/Tasty/Plutarch/Property.hs [hunk 6]
```diff
@@ -102,6 +105,38 @@ peqProperty expected gen shr comp =
...
+ @since 1.0.1
+-}
+alwaysFailProperty ::
+    forall (a :: Type) (c :: S -> Type) (d :: S -> Type).
+    ( Show a
+    , PLifted c ~ a
+    , PUnsafeLiftDecl c
+    ) =>
+    Gen a ->
+    -- | A shrinker for inputs.
```
Comment (kozross) [inline src/Test/Tasty/Plutarch/Property.hs]: I think this is fairly self-evident.

File: src/Test/Tasty/Plutarch/Property.hs [hunk 7]
```diff
@@ -102,6 +105,38 @@ peqProperty expected gen shr comp =
...
+    (a -> [a]) ->
+    -- | The computation to test.
```
Comment (kozross) [inline src/Test/Tasty/Plutarch/Property.hs]: Likewise here.

**Review by kozross — CHANGES_REQUESTED** [review]

File: src/Test/Tasty/Plutarch/Property.hs (hunk 3 above)
Comment (SeungheonOh) [reply src/Test/Tasty/Plutarch/Property.hs]: Yeah I forgot to change it :+1:

File: src/Test/Tasty/Plutarch/Property.hs [hunk 8]
```diff
@@ -102,6 +105,38 @@ peqProperty expected gen shr comp =
                 Left e -> unexpectedError e
                 Right s' -> sameAsExpected s'
 
+{- | 'alwaysFailProperty' universally checks if given computation fails.
+ This runs the given script with generated input; it makes sure that
+ script fails by crashes or errors.  Since output does not need to be
+ checked, `PEq` instance is not required.
```
Comment (kozross) [inline src/Test/Tasty/Plutarch/Property.hs]: The last sentence isn't really necessary IMHO.

**Review by kozross — CHANGES_REQUESTED** [review]

File: src/Test/Tasty/Plutarch/Property.hs (hunk 8 above)
Comment (SeungheonOh) [reply src/Test/Tasty/Plutarch/Property.hs]: yes agreed

**Review by kozross — APPROVED** [review]
