### PR TITLE
Fixed to have correct log message / Test cases for different handler situations

### LINKED ISSUE #5: Logs are not provided in certain cases
Here, testing failed due to script running without failure while it was expected to fail. In this specific case, log will not be provided at all.

```hs
expected :: Term s (PBuiltinPair PTreasuryWithdrawalDatum PTxInfo :--> PMaybe PUnit)
expected = plam $ \_input -> unTermCont $ do
  -- Test cases are all expected to fail
  return $ pcon $ PNothing

definition :: Term s (PBuiltinPair PTreasuryWithdrawalDatum PTxInfo :--> PUnit)
definition = plam $ \input -> unTermCont $ do
                                  pure $ ptrace "hello world, this message should be printed"
                                  bla bla bla 
```

Screenshot_20220515_220643

### PR DESCRIPTION
**Pull request by SeungheonOh**
- Fixed #5, it presents correct log message when property is expected to fail but script succeeds
Issue was the use of negative number; negative number made an incorrect comparison. Check added comment for more information.

- Added `handlers-tests` that checks all possible outputs of `classifiedProperty`. Check the following result. 
```
Possible outputs of classifiedProperty
  "expected: Failure/yields: Success":               FAIL (expected: expects failure but script runs successfully)
    *** Failed! Falsified (after 3 tests and 2 shrinks):
    Generated input 2
    No logs found.
    Did you forget to build Plutarch with +development?
    A case which should have crashed ran successfully instead.
    Use --quickcheck-replay=475499 to reproduce. (expected failure)
  "expected: Failure/yields: Failure":               OK (0.16s)
    +++ OK, passed 6400 tests:
    50.31% OddNumber
    49.69% EvenNumber
  "expected: Success/yields: Failure":               FAIL (expected: expects success but script crashed)
    *** Failed! Falsified (after 1 test):
    Generated input 0
    No logs found.
    Did you forget to build Plutarch with +development?
    Expected a successful run, but crashed instead.
    Error details
                                                        An error has occurred:  User error:
    The provided Plutus code called 'error'.
    Use --quickcheck-replay=606309 to reproduce. (expected failure)
  "expected: Success/yields: Success but Incorrect": FAIL (expected: Yielded value is incorrect)
    *** Failed! Falsified (after 1 test):
    Generated input 1
    No logs found.
    Did you forget to build Plutarch with +development?
    Test script result does not match expected value.
    Use --quickcheck-replay=808582 to reproduce. (expected failure)
  "expected: Success/yields: Success and Correct":   OK (0.13s)
    +++ OK, passed 6400 tests:
    51.09% EvenNumber
    48.91% OddNumber

All 5 tests passed (0.16s)
```

### CODE REVIEW

File: examples/handlers-tests/Main.hs [hunk 1]
```diff
@@ -0,0 +1,111 @@
+{- | Module: Main
+ Copyright: (C) Liqwid Labs 2022
+ License: Apache 2.0
+ Portability: GHC only
+ Stability: Experimental
+
+ Example of @plutarch-quickcheck@ tests. These are meant to be read as source
+ code.
+-}
+module Main (main) where
```
Comment (kozross) [inline examples/handlers-tests/Main.hs:14]: This needs a bit more explanation, similar to the other examples.

**Review by kozross — CHANGES_REQUESTED** [review]

**Review by kozross — APPROVED** [review]
